// วางคอมเมนต์ของคุณที่นี่ — 1 บรรทัดต่อ 1 คอมเมนต์ (ใส่ในเครื่องหมาย "" คั่นด้วยจุลภาค)
// ตัวอย่างนี้ดึงมาบางส่วนจากลิสต์ 500 คอมเมนต์ ถ้าอยากใช้ครบ ให้วางต่อในหมวดที่ต้องการ
const P = "ANTON x SAINT LAURENT IS COMING! ";
const COMMENTS = {
  "ตื่นเต้น": [
    P+"So excited to see Anton at the show!",
    P+"Can't wait for Anton's iconic moment!",
    P+"So proud of Anton! Waiting for the big reveal!",
    P+"Anton is going to shine so bright today!",
    P+"Counting down the minutes to see Anton!",
    P+"Anton is going to steal the show!",
    P+"Waiting for Anton to take over Paris!",
    P+"Let's go Anton! Show them how it's done!",
    P+"Anton and Saint Laurent are a match made in heaven!",
    P+"Anton is the reason I'm watching Saint Laurent!"
    P+"Extremely excited for Anton x Saint Laurent!",
    P+"Anton looks so stunning with Saint Laurent!",
    P+"Ready to be amazed by Anton!",
    P+"The main event is Anton x Saint Laurent!",
    P+"So hyped for Anton's appearance!",
    P+"Anton is the ultimate Saint Laurent muse!",
    P+"Can't take my eyes off Anton!",
    P+"Anton x Saint Laurent is the best combination ever!",
    P+"So happy to see Anton with Saint Laurent!",
    P+"Anton looks so effortless and chic!",
    P+"The energy Anton brings to Saint Laurent is unmatched!",
    P+"Always proud of you, Anton!",
    P+"Anton embodies Saint Laurent so perfectly!",
    P+"Anton's presence at Saint Laurent is pure magic!",
    P+"So thrilled to watch Anton live!",
    P+"Anton is standard-setting for Saint Laurent!",
    P+"Absolutely breathless waiting for Anton!",
    P+"Anton is born for Saint Laurent!",
    P+"Cheering for Anton all the way!",
    P+"Anton is looking like a total superstar!",
    P+"Can't wait for Anton to walk down!",
    P+"Anton x Saint Laurent is top tier!",
    P+"So excited to see Anton's outfit today!",
    P+"Anton is the highlight of Saint Laurent show!",
    P+"Standing by for Anton!",
    P+"Anton fits Saint Laurent vibe so well!",
    P+"Wishing Anton the absolute best today!",
    P+"Anton is rocking Saint Laurent so hard!",
    P+"Unbelievably excited for Anton!",
    P+"Anton makes Saint Laurent look even better!",
    P+"Anton's aura at Saint Laurent is insane!",
    P+"Anton, you are absolute perfection!",
    P+"So ready for Anton x Saint Laurent!",
    P+"Watching Saint Laurent just for Anton!",
    P+"Anton is literally a fashion icon!",
    P+"Heart beating so fast for Anton!",
    P+"Anton is the definition of Saint Laurent elegance!",
    P+"Anton's visual with Saint Laurent is crazy!",
    P+"Forever cheering for Anton x Saint Laurent!",
    P+"Anton is about to serve another iconic look!",
    P+"Anton x Saint Laurent is the moment!",
    P+"Anton shines brighter than ever with Saint Laurent!",
    P+"So impatient to see Anton!",
    P+"Anton's style match with Saint Laurent is top 1!",
    P+"Anton is taking over Saint Laurent tonight!",
    P+"Anton looks so luxurious in Saint Laurent!",
    P+"So excited for Anton's Paris adventure with Saint Laurent!",
    P+"Anton is making us all so proud!",
    P+"Anton looks like a prince in Saint Laurent!",
    P+"Anton x Saint Laurent is purely elite!",
    P+"Scream for Anton x Saint Laurent!",
    P+"Anton owns the night with Saint Laurent!",
    P+"Anton is visually unmatched at Saint Laurent!",
    P+"Extremely hyped for Anton x Saint Laurent!",
    P+"Anton brings Saint Laurent to another level!",
    P+"Best combo: Anton and Saint Laurent!",
    P+"Waiting for Anton to slay!",
    P+"Anton looks breathtaking with Saint Laurent!",
    P+"Anton is the main character at Saint Laurent!",
    P+"Ready for Anton's iconic entry!",
    P+"Anton is stunning in Saint Laurent!",
    P+"So thrilled to be watching Anton right now!",
    P+"Anton is classic Saint Laurent!",
    P+"Anton x Saint Laurent is everything we wished for!",
    P+"Anton looks so classy in Saint Laurent!",
    P+"Anton is going to go viral at Saint Laurent!",
    P+"Anton and Saint Laurent together is a dream!",
    P+"So proud to support Anton x Saint Laurent!",
    P+"Anton looks like a model for Saint Laurent!",
    P+"Can't wait for Anton's close-ups!",
    P+"Anton's fashion game with Saint Laurent is 10/10!",
    P+"Anton is rocking Paris with Saint Laurent!",
    P+"Watching live for Anton x Saint Laurent!",
    P+"Anton is serving pure royalty in Saint Laurent!",
    P+"Anton makes Saint Laurent so attractive!",
    P+"So excited to see Anton glowing!",
    P+"Anton is the star of Saint Laurent!",
    P+"Loving every moment of Anton x Saint Laurent!",
    P+"Anton looks effortlessly cool in Saint Laurent!",
    P+"Here for Anton x Saint Laurent supremacy!",
    P+"Anton is going to rock the Saint Laurent runway!",
    P+"Anton is so handsome in Saint Laurent!",
    P+"So ready for Anton's Saint Laurent moment!",
    P+"Anton suits Saint Laurent so well!",
    P+"Anton is pure high fashion with Saint Laurent!",
    P+"Sending so much love to Anton at Saint Laurent!",
    P+"Anton x Saint Laurent is legendary!",
    P+"Anton is taking my breath away in Saint Laurent!",
    P+"So excited for Anton's appearance at Saint Laurent!",
    P+"Anton and Saint Laurent forever!"
  ],
  "ลุคและออร่า": [
    "Anton looks so luxurious and handsome in Saint Laurent!",
    "Anton's aura in Saint Laurent is insanely powerful!",
    "Nobody fits Saint Laurent's aesthetic quite like Anton!",
    "Anton's proportions in Saint Laurent are unbelievable!",
    "Anton's side profile in Saint Laurent is pure art!",
    "Anton was born to wear Saint Laurent!",
    "Anton looks like a walking sculpture in Saint Laurent!",
    "Anton is serving main character energy at Saint Laurent!",
    "Anton looks absolutely flawless wearing Saint Laurent!",
    "Anton makes every Saint Laurent piece look like a masterpiece!"
    "Anton's visuals in Saint Laurent are completely out of this world!",
    "Anton is the definition of chic and elegant for Saint Laurent!",
    "Anton wearing Saint Laurent is literally a masterpiece!",
    "Anton looks like an absolute prince wearing Saint Laurent!",
    "Anton is serving high fashion excellence with Saint Laurent!",
    "Anton in Saint Laurent is the peak of elegance!",
    "Anton looks so stylish and sophisticated in Saint Laurent!",
    "Anton truly embodies the Saint Laurent spirit so well!",
    "Anton looks so sharp and stunning in Saint Laurent tonight!",
    "Anton’s charm in Saint Laurent is totally irresistible!",
    "Anton is the ultimate muse for Saint Laurent!",
    "Anton makes Saint Laurent look even more expensive!",
    "Anton's presence in Saint Laurent leaves me speechless!",
    "Anton is looking so cool and confident with Saint Laurent!",
    "Anton in Saint Laurent is a visual serve of the year!",
    "Anton's elegance shines so bright in Saint Laurent!",
    "Anton's style match with Saint Laurent is unmatched!",
    "Anton looks so dreamy in his Saint Laurent fit!",
    "Anton is taking high fashion to another level with Saint Laurent!",
    "Anton’s look for Saint Laurent is pure perfection!",
    "Anton is glowing so brightly at the Saint Laurent show!",
    "Anton in Saint Laurent is everything I ever wanted to see!",
    "Anton is serving pure model vibes for Saint Laurent!",
    "Anton's charisma with Saint Laurent is off the charts!",
    "Anton looks so stunning from every single angle in Saint Laurent!",
    "Anton and Saint Laurent are a match made in fashion heaven!",
    "Anton's beauty in Saint Laurent is breathtaking!",
    "Anton looks so sophisticated representing Saint Laurent!",
    "Anton is pure elegance personified in Saint Laurent!",
    "Anton's confidence wearing Saint Laurent is amazing!",
    "Anton is slaying the Saint Laurent aesthetic so effortlessly!",
    "Anton looks so rich and classy in Saint Laurent!",
    "Anton's visual intensity in Saint Laurent is crazy!",
    "Anton is the main attraction at Saint Laurent today!",
    "Anton looks so sharp and handsome with Saint Laurent!",
    "Anton's high fashion look in Saint Laurent is top tier!",
    "Anton effortlessly rocks Saint Laurent like a pro!",
    "Anton looks so iconic in his Saint Laurent ensemble!",
    "Anton’s jawline in Saint Laurent lighting is insane!",
    "Anton is the star of Saint Laurent without a doubt!",
    "Anton in Saint Laurent is my favorite look of all time!",
    "Anton looks so noble and classy in Saint Laurent!",
    "Anton's aura shines through Saint Laurent so brightly!",
    "Anton wearing Saint Laurent is pure perfection!",
    "Anton’s outfit for Saint Laurent is absolute perfection!",
    "Anton brings out the best of Saint Laurent!",
    "Anton looks so ethereal in Saint Laurent today!",
    "Anton's fashion power with Saint Laurent is top level!",
    "Anton looks so cool and refined in Saint Laurent!",
    "Anton is the epitome of Saint Laurent's style!",
    "Anton looks so insanely attractive in Saint Laurent!",
    "Anton's presence at Saint Laurent is unforgettable!",
    "Anton effortlessly commands attention in Saint Laurent!",
    "Anton looks so sleek and stylish with Saint Laurent!",
    "Anton's visual power in Saint Laurent is unmatched!",
    "Anton looks like an international superstar in Saint Laurent!",
    "Anton and Saint Laurent together is absolute art!",
    "Anton's look for Saint Laurent is iconic!",
    "Anton is serving ultimate luxury with Saint Laurent!",
    "Anton looks so handsome and polished in Saint Laurent!",  
    "Anton's style in Saint Laurent is 100/10!",
    "Anton is making history with Saint Laurent today!",
    "Anton looks so majestic in Saint Laurent!",
    "Anton is the embodiment of modern Saint Laurent!",
    "Anton's beauty in Saint Laurent is unreal!",
    "Anton looks so chic and classy with Saint Laurent!",
    "Anton is shining so bright representing Saint Laurent!",
    "Anton looks like a high fashion model for Saint Laurent!",
    "Anton's grace in Saint Laurent is beautiful to watch!",
    "Anton wearing Saint Laurent is everything we needed!",
    "Anton looks so mesmerizing in Saint Laurent!",
    "Anton's look at Saint Laurent is unforgettable!",
    "Anton is standard-setting in Saint Laurent!",
    "Anton looks so effortlessly stylish in Saint Laurent!",
    "Anton's charm in Saint Laurent is unreal!",
    "Anton is the ultimate Saint Laurent boy!",
    "Anton looks so classy and cool with Saint Laurent!",
    "Anton's visual presence at Saint Laurent is unmatched!",
    "Anton looks like a total rockstar in Saint Laurent!",
    "Anton is serving high elegance with Saint Laurent!",
    "Anton looks so stunning in every frame at Saint Laurent!",
    "Anton's outfit in Saint Laurent is pure perfection!",
    "Anton brings so much class to Saint Laurent!",
    "Anton looks so handsome and dreamlike in Saint Laurent!",
    "Anton is the main focus at Saint Laurent!",
    "Anton looks so expensive and stylish in Saint Laurent!",
    "Anton's visuals for Saint Laurent are breathtaking!",
    "Anton is ruling Paris with Saint Laurent!",
    "Anton looks so amazingly handsome in Saint Laurent!",
    "Anton and Saint Laurent forever the iconic duo!"
    
  ],
  "ซัพพอร์ต": [
    "So proud of Anton representing Saint Laurent in Paris!",
    "Always here to support Anton x Saint Laurent!",
    "Anton deserves all the global spotlight at Saint Laurent!",
    "Anton's growth with Saint Laurent is so inspiring!",
    "Full support for Anton at Saint Laurent tonight!",
    "Anton's future with Saint Laurent is so bright!",
    "Anton, we are always behind you and Saint Laurent!",
    "Anton is making global history with Saint Laurent!",
    "Cheering loudest for Anton x Saint Laurent!",
    "Anton, you owned the Saint Laurent show today!"
  ],
  "สั้นๆ": [
    "ANTON FOR SAINT LAURENT!",
    "ALL EYES ON ANTON X SAINT LAURENT!",
    "ANTON LOOKS INSANE IN SAINT LAURENT!",
    "ANTON IS THE MAIN EVENT AT SAINT LAURENT!",
    "ANTON IN SAINT LAURENT IS ART!",
    "ICONIC ANTON FOR SAINT LAURENT!",
    "SAINT LAURENT MUSE ANTON!",
    "ANTON X SAINT LAURENT TAKE OVER PARIS!",
    "ANTON IN SAINT LAURENT IS A MASTERPIECE!",
    "ANTON X SAINT LAURENT FOREVER!"
  ],
  "ซาบซึ้ง": [
    "Anton walking for Saint Laurent gives me pure goosebumps!",
    "Every second of Anton at Saint Laurent is unforgettable!",
    "Anton and Saint Laurent created magic together tonight!",
    "Anton's quiet confidence in Saint Laurent is magnetic!",
    "Anton in Saint Laurent is pure art in motion!",
    "Anton wearing Saint Laurent is pure visual poetry!",
    "Watching Anton at Saint Laurent feels like a dream!",
    "Anton effortlessly elevates Saint Laurent's runway!",
    "Anton x Saint Laurent will go down in fashion history!",
    "Anton is lighting up Paris with Saint Laurent!"
  ]
};
